### ISSUE TITLE
能不能给@Safe加上监听呢

### ISSUE THREAD

**Issue by suo801** [fengzhizi715/SAF-AOP#9]
一旦报错可以在Appliacation后者一个全局的地方加上监听，比如发生报错我可以想友盟统计发送一个自定义异常，这样可以监听用户使用情况

**Comment by fengzhizi715** [comment]
hi @suo801 我抽空更新一下，周末或者下周初的样子。

**Comment by suo801** [comment]
好的，非常感谢。还有再加个动态申请权限的，棒棒哒

**Comment by fengzhizi715** [comment]
hi @suo801 @Safe的回调已经支持，可以看例子。Kotlin应该也已经支持了。
有问题随时联系我，WeChat：fengzhizi715

**Comment by fengzhizi715** [comment]
另外，申请权限的还没有添加，1-2天内抽空添加

**Comment by suo801** [comment]
点赞！
